export const themeDirectory: Theme[] = [
    {
      id: 1,
      title: 'Начало работы',
      header: 'Для новичка + Основы работы',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 8,
      totalTasks: 10,
      buttonProgress: 'Продолжить тему',
      category: "-",
      status: false,
    },
    {
      id: 2,
      title: 'Работа с библиотеками GPN',
      header: 'Профессионалу + Библиотеки',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 0,
      totalTasks: 225,
      buttonProgress: 'Начать',
      category: "Библиотеки",
      status: false,
    },
    {
      id: 3,
      title: 'Введение в рабочую среду ',
      header: 'Профессионалу + Библиотеки',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 0,
      totalTasks: 10,
      buttonProgress: 'Начать',
      category: "Рабочая среда",
      status: false,
    },
    {
      id: 4,
      title: 'Начало работы',
      header: 'Для новичка + Основы работы',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 3,
      totalTasks: 10,
      buttonProgress: 'Продолжить тему',
      category: "-",
      status: false,
    },
    {
      id: 5,
      title: 'Работа с библиотеками GPN',
      header: 'Профессионалу + Библиотеки',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 0,
      totalTasks: 225,
      buttonProgress: 'Начать',
      category: "Библиотеки",
      status: false,
    },
    {
      id: 6,
      title: 'Введение в рабочую среду ',
      header: 'Профессионалу + Библиотеки',
      text: 'Познакомьтесь ближе с компанией и узнайте больше о том, что вы делаете',
      completedTasks: 0,
      totalTasks: 10,
      buttonProgress: 'Начать',
      category: "Рабочая среда",
      status: false,
    },
  ];
  